function picture = predictionStep(fullpicture,p);
picture=fullpicture;
picture(2:2:end,:) = fullpicture(2:2:end,:)...
    +p*(fullpicture(1:2:end,:)...
    +[fullpicture(3:2:end,:);...
    fullpicture(end-1,:)]);
